version: '3.9'

services:
  eduweconnect-notification:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eduweconnect-notification
    ports:
      - "7003:7003"
    env_file:
      - .env.${NODE_ENV:-development}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
